# Generated by Django 5.1.1 on 2024-10-21 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kolesa', '0002_alter_car_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='purchased_cars',
            field=models.ManyToManyField(blank=True, null=True, related_name='cars', to='kolesa.car'),
        ),
    ]
