# Generated by Django 5.1.1 on 2024-10-21 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kolesa', '0003_alter_customer_purchased_cars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='purchased_cars',
            field=models.ManyToManyField(related_name='cars', to='kolesa.car'),
        ),
    ]
